###

POST localhost:8080/api/member/signup
Content-Type: application/json

{
  "loginId" : "n",
  "password" : "qwer1234!",
  "name" : "name",
  "email": "d@d.c",
  "dormType": "GounA"
}

###
POST localhost:8080/api/member/login
Content-Type: application/json

{
  "loginId" : "n",
  "password" : "qwer1234!"
}
###