###
POST localhost:8080/api/member/signup
Content-Type: application/json

{
  "id": "pospos",
  "password": "QWERqwerqwer1234!@#$",
  "email": "test@test.sog",
  "dormType": "GOA",
  "name": "POPOS"
}


###

